@startuml;
Command -> Entity: ask to do something;
Entity -> Entity: validates, creates events\n(not stored yet);
Entity -> Journal: stores events;
Entity -> Command: response;
Entity -> Journal: ask for not applied events;
Entity -> Entity: events are applied and state is changed;
@enduml;